// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nGDqHaYZo4FJYSN4xzLGB9
// Component: Ucie_n-Eoak1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import PageLayout from "../../PageLayout"; // plasmic-import: YaqyW3PDeE8P/component
import { AntdDatePicker } from "@plasmicpkgs/antd5/skinny/registerDatePicker"; // plasmic-import: lKdkQL67fv/codeComponent
import { datePickerHelpers as AntdDatePicker_Helpers } from "@plasmicpkgs/antd5/skinny/registerDatePicker"; // plasmic-import: lKdkQL67fv/codeComponentHelper
import Statistic from "../../Statistic"; // plasmic-import: l_KrbdcsHkLJ/component
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect"; // plasmic-import: OvH7ENd3m7ug/codeComponent
import { SimpleChart } from "@plasmicpkgs/react-chartjs-2"; // plasmic-import: 0Qywk3bhW-8/codeComponent
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources"; // plasmic-import: dKO1ZxBb59t1/codeComponent

import { useScreenVariants as useScreenVariantsznrVnsc7MCN } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZNRVnsc7mC_n/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_dashboard.module.css"; // plasmic-import: nGDqHaYZo4FJYSN4xzLGB9/projectcss
import sty from "./PlasmicBusinessMetrics.module.css"; // plasmic-import: Ucie_n-Eoak1/css

createPlasmicElementProxy;

export type PlasmicBusinessMetrics__VariantMembers = {};
export type PlasmicBusinessMetrics__VariantsArgs = {};
type VariantPropType = keyof PlasmicBusinessMetrics__VariantsArgs;
export const PlasmicBusinessMetrics__VariantProps =
  new Array<VariantPropType>();

export type PlasmicBusinessMetrics__ArgsType = {};
type ArgPropType = keyof PlasmicBusinessMetrics__ArgsType;
export const PlasmicBusinessMetrics__ArgProps = new Array<ArgPropType>();

export type PlasmicBusinessMetrics__OverridesType = {
  root?: p.Flex<"div">;
  pageLayout?: p.Flex<typeof PageLayout>;
  h1?: p.Flex<"h1">;
  start?: p.Flex<typeof AntdDatePicker>;
  end?: p.Flex<typeof AntdDatePicker>;
  select?: p.Flex<typeof AntdSelect>;
};

export interface DefaultBusinessMetricsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBusinessMetrics__RenderFunc(props: {
  variants: PlasmicBusinessMetrics__VariantsArgs;
  args: PlasmicBusinessMetrics__ArgsType;
  overrides: PlasmicBusinessMetrics__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "start.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: p.generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      },
      {
        path: "end.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``,

        onMutate: p.generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "month"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    topRevByCountryInDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "6pAWQhVNr8t7v7gDuWQuQE",
        opId: "769f3f40-1ec6-4a9e-8efa-bb58e3042871",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: "plasmic.$..$..$.769f3f40-1ec6-4a9e-8efa-bb58e3042871.$.",
        invalidatedKeys: null,
        roleId: null
      };
    }),
    ordersByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "6pAWQhVNr8t7v7gDuWQuQE",
        opId: "50f38251-bb69-4680-899c-a7e67b993a54",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: "plasmic.$..$..$.50f38251-bb69-4680-899c-a7e67b993a54.$.",
        invalidatedKeys: null,
        roleId: null
      };
    }),
    signupsByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "6pAWQhVNr8t7v7gDuWQuQE",
        opId: "6d6f7474-ce1f-4eb7-b9a6-8d58956e67e6",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: "plasmic.$..$..$.6d6f7474-ce1f-4eb7-b9a6-8d58956e67e6.$.",
        invalidatedKeys: null,
        roleId: null
      };
    }),
    totalRevByCustomDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "6pAWQhVNr8t7v7gDuWQuQE",
        opId: "1eff0b97-83b2-40cb-8d6d-1a3626a7ffa6",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: "plasmic.$..$..$.1eff0b97-83b2-40cb-8d6d-1a3626a7ffa6.$.",
        invalidatedKeys: null,
        roleId: null
      };
    }),
    monthlyRevByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "6pAWQhVNr8t7v7gDuWQuQE",
        opId: "4f19b976-dfcf-4663-84a6-cf63f573229f",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: "plasmic.$..$..$.4f19b976-dfcf-4663-84a6-cf63f573229f.$.",
        invalidatedKeys: null,
        roleId: null
      };
    }),
    quarterlyRevByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "6pAWQhVNr8t7v7gDuWQuQE",
        opId: "8acdc718-1519-416d-a608-6bf531378328",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: "plasmic.$..$..$.8acdc718-1519-416d-a608-6bf531378328.$.",
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
  }

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsznrVnsc7MCN()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <React.Fragment>
                  <section
                    className={classNames(projectcss.all, sty.section__eItNc)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xuDfb)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Business Metrics"}
                      </h1>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section___39Nto)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wkhrj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___0XC49
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__ifBQz
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Custom date range analysis"}
                            </span>
                          </React.Fragment>
                        </h2>
                      </div>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bPbmu
                        )}
                      >
                        {(() => {
                          const child$Props = {
                            allowClear: true,
                            bordered: true,
                            className: classNames("__wab_instance", sty.start),
                            onChange:
                              p.generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["start", "value"],
                                AntdDatePicker_Helpers
                              ),
                            picker: "date",
                            popupBodyClassName: classNames({
                              [sty["pcls_1D6_KYLXBToD"]]: true
                            }),
                            popupClassName: classNames({
                              [sty["pcls_IR9AOnILB_Hu"]]: true
                            }),
                            popupHeaderClassName: classNames({
                              [sty["pcls_gXDaiyNZsj68"]]: true
                            }),
                            popupScopeClassName: sty["start__datePickerPopup"],
                            showTime: false,
                            value: p.generateStateValueProp($state, [
                              "start",
                              "value"
                            ])
                          };
                          p.initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "start.value"
                              }
                            ],
                            [],
                            AntdDatePicker_Helpers ?? {},
                            child$Props
                          );

                          return (
                            <AntdDatePicker
                              data-plasmic-name={"start"}
                              data-plasmic-override={overrides.start}
                              {...child$Props}
                            />
                          );
                        })()}
                        {(() => {
                          const child$Props = {
                            allowClear: true,
                            bordered: true,
                            className: classNames("__wab_instance", sty.end),
                            defaultValue: ``,
                            onChange:
                              p.generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["end", "value"],
                                AntdDatePicker_Helpers
                              ),
                            picker: "date",
                            popupScopeClassName: sty["end__datePickerPopup"],
                            value: p.generateStateValueProp($state, [
                              "end",
                              "value"
                            ])
                          };
                          p.initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "end.value"
                              }
                            ],
                            [],
                            AntdDatePicker_Helpers ?? {},
                            child$Props
                          );

                          return (
                            <AntdDatePicker
                              data-plasmic-name={"end"}
                              data-plasmic-override={overrides.end}
                              {...child$Props}
                            />
                          );
                        })()}
                      </p.Stack>
                    </div>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__nw9Sm)}
                    >
                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__jkpl9
                        )}
                        hideTrendTracker={true}
                        number={
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__nUdtw
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $queries.signupsByDateRange.data[0]
                                    .signup_count;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </h2>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___0AyI4
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___5TIgd
                              )}
                              style={(() => {
                                try {
                                  return undefined;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return undefined;
                                  }
                                  throw e;
                                }
                              })()}
                            >
                              {"Sign-ups"}
                            </div>
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__vw7LI)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/dashboard/images/image7.svg",
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__ow3NX
                        )}
                        hideTrendTracker={true}
                        number={
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2___8DlPo
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $queries.ordersByDateRange.data[0]
                                    .order_count;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </h2>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qBl20
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xkQm
                              )}
                            >
                              {"Orders"}
                            </div>
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__xJueg)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/dashboard/images/orderIcon.svg",
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__nMfh7
                        )}
                        hideTrendTracker={true}
                        number={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__dmq1O
                            )}
                          >
                            <h2
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                projectcss.__wab_text,
                                sty.h2__xgNy8
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return (
                                      "$" +
                                      Intl.NumberFormat("en").format(
                                        $queries.totalRevByCustomDateRange
                                          .data[0].total_revenue
                                      )
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "NULL";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </h2>
                          </div>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___9W7Qg
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__iuUwO
                              )}
                            >
                              {"Revenue"}
                            </div>
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__xvkLl)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/dashboard/images/dollarIcon.svg",
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />
                    </p.Stack>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__fw3G8)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__iYvLd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jaLok
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2___4R2
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Revenue Trends"}
                            </span>
                          </React.Fragment>
                        </h2>
                        <AntdSelect
                          data-plasmic-name={"select"}
                          data-plasmic-override={overrides.select}
                          bordered={true}
                          className={classNames("__wab_instance", sty.select)}
                          defaultOpen={false}
                          defaultStylesClassName={classNames(
                            projectcss.root_reset,
                            projectcss.plasmic_default_styles,
                            projectcss.plasmic_mixins,
                            projectcss.plasmic_tokens,
                            plasmic_antd_5_hostless_css.plasmic_tokens
                          )}
                          defaultValue={"month"}
                          onChange={p.generateStateOnChangeProp($state, [
                            "select",
                            "value"
                          ])}
                          options={(() => {
                            const __composite = [
                              { value: null, label: null, type: null },
                              { value: null, label: null, type: "option" }
                            ];
                            __composite["0"]["value"] = "month";
                            __composite["0"]["label"] = "month";
                            __composite["0"]["type"] = "option";
                            __composite["1"]["value"] = "quarterly";
                            __composite["1"]["label"] = "quarterly";
                            return __composite;
                          })()}
                          placeholder={"Select..."}
                          popupScopeClassName={sty["select__popup"]}
                          value={p.generateStateValueProp($state, [
                            "select",
                            "value"
                          ])}
                        />
                      </div>
                      <SimpleChart
                        className={classNames(
                          "__wab_instance",
                          sty.chart__axoLd
                        )}
                        data={
                          $state.select.value === "month"
                            ? $queries.monthlyRevByDateRange.data
                            : $queries.quarterlyRevByDateRange.data
                        }
                        interactive={false}
                        title={``}
                        type={"bar"}
                      />
                    </p.Stack>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__bmfve)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__z2Jcl)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__liIcj
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__fP97B
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Revenue per country: within the last year"}
                            </span>
                          </React.Fragment>
                        </h2>
                      </div>
                      <SimpleChart
                        className={classNames(
                          "__wab_instance",
                          sty.chart__liDl
                        )}
                        data={$queries.topRevByCountryInDateRange.data}
                        interactive={false}
                        labelField={"country"}
                        title={"Revenue by country"}
                        type={"bar"}
                      />
                    </p.Stack>
                  </section>
                </React.Fragment>
              )}
            </ph.DataCtxReader>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "h1", "start", "end", "select"],
  pageLayout: ["pageLayout", "h1", "start", "end", "select"],
  h1: ["h1"],
  start: ["start"],
  end: ["end"],
  select: ["select"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  h1: "h1";
  start: typeof AntdDatePicker;
  end: typeof AntdDatePicker;
  select: typeof AntdSelect;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBusinessMetrics__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBusinessMetrics__VariantsArgs;
    args?: PlasmicBusinessMetrics__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBusinessMetrics__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBusinessMetrics__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBusinessMetrics__ArgProps,
          internalVariantPropNames: PlasmicBusinessMetrics__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBusinessMetrics__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBusinessMetrics";
  } else {
    func.displayName = `PlasmicBusinessMetrics.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <p.PlasmicPageGuard
      minRole={null}
      appId={"nGDqHaYZo4FJYSN4xzLGB9"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </p.PlasmicPageGuard>
  );

  return PageGuard;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "nGDqHaYZo4FJYSN4xzLGB9"
    });

    return (
      <p.PlasmicDataSourceContextProvider
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </p.PlasmicDataSourceContextProvider>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicBusinessMetrics = Object.assign(
  // Top-level PlasmicBusinessMetrics renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    h1: makeNodeComponent("h1"),
    start: makeNodeComponent("start"),
    end: makeNodeComponent("end"),
    select: makeNodeComponent("select"),

    // Metadata about props expected for PlasmicBusinessMetrics
    internalVariantProps: PlasmicBusinessMetrics__VariantProps,
    internalArgProps: PlasmicBusinessMetrics__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBusinessMetrics;
/* prettier-ignore-end */
